### ISSUE TITLE
Farben

### ISSUE THREAD

**Issue by henk789** [tjarbo/arbeitszeiten#1]
Ich würde die schwarze Schrift auf dem grünen und gelben Hintergrund irgendwie anders machen, evtl. die Transparenz auf 60% oder so oder halt weiß und die Farben kräftiger xD

**Comment by henk789** [comment]
#nixZuTunInDerSchule

**Comment by tjarbo** [comment]
Mehr als ein Jahr später ist es endlich soweit und ich habe die Oberfläche nochmal überarbeitet und Bulma anstatt W3.CSS verwendet xD Hoffe so sieht es angenehmer aus. 

Danke für die Tipps 🙌

**Comment by henk789** [comment]
sieht schick aus
